name: AIInterviewApp
options:
  bundleIdPrefix: com.aiinterview.app
targets:
  AIInterviewApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: AIInterviewApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aiinterview.app
        DEVELOPMENT_TEAM: ""
        INFOPLIST_FILE: Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
        SWIFT_VERSION: 5.0
        ENABLE_PREVIEWS: true
        CODE_SIGN_STYLE: Automatic
configs:
  debug:
    inheritance: none
    base:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      DEBUG_INFORMATION_FORMAT: dwarf
      GCC_PREPROCESSOR_DEFINITIONS: "DEBUG=1 $(inherited)"
  release:
    inheritance: none
    base:
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
      ENABLE_NS_ASSERTIONS: NO